"""Messages - the audit log and cost ledger - and the replies and questions built on them."""

from __future__ import annotations

from typing import Any

from peewee import SqliteDatabase

from ..db import HUMAN, now
from ..models import Message, rows
from .agents import get_agent
from .common import bound
from .deps import add_dependency, blocking_dependencies
from .lifecycle import TRANSITIONS, transition
from .tasks import add_task, get_task


@bound
def send_message(
    db: SqliteDatabase,
    sender: str,
    recipient: str,
    task_id: int | None,
    msg_type: str,
    payload: str,
    input_tokens: int = 0,
    output_tokens: int = 0,
    cache_read_tokens: int = 0,
    cache_write_tokens: int = 0,
    tool_rounds: int = 0,
    cost_usd: float = 0.0,
) -> int:
    """Log a message and record its cost.

    Messages are the audit trail and cost ledger: every agent communication is
    tracked here. A message stays unread until a run of the recipient's has
    seen it and succeeded (the daemon marks it then), or an operator reads its
    inbox.

    Args:
        db: SqliteDatabase instance for this project.
        sender: Agent or "human" sending the message.
        recipient: Agent or "human" receiving the message.
        task_id: Associated task (optional).
        msg_type: Message classification (e.g., "request", "result", "question").
        payload: Message content (may be JSON, markdown, or plain text).
        input_tokens: Fresh input tokens, charged at full price.
        output_tokens: Tokens generated by the LLM output.
        cache_read_tokens: Input served from cache, at roughly a tenth the price.
        cache_write_tokens: Input written to cache, at roughly 1.25x the price.
        tool_rounds: API round-trips in this turn.
        cost_usd: Direct cost in USD (if applicable).

    Returns:
        int: New message ID.

    Examples:
        >>> msg_id = send_message(db, "claude-worker", "human", 42, "result",
        ...                        "Task completed", input_tokens=100, output_tokens=50)
    """
    message = Message.create(
        ts=now(),
        sender=sender,
        recipient=recipient,
        task_id=task_id,
        msg_type=msg_type,
        payload=payload,
        input_tokens=input_tokens,
        output_tokens=output_tokens,
        cache_read_tokens=cache_read_tokens,
        cache_write_tokens=cache_write_tokens,
        tool_rounds=tool_rounds,
        cost_usd=cost_usd,
    )
    return int(message.id)


def reply(
    db: SqliteDatabase,
    agent_name: str,
    task_id: int | None,
    payload: str,
    input_tokens: int = 0,
    output_tokens: int = 0,
    cache_read_tokens: int = 0,
    cache_write_tokens: int = 0,
    tool_rounds: int = 0,
    cost_usd: float = 0.0,
    status: str = "done",
) -> int:
    """Log a task result back to the human and update the task status.

    Sends a message to the human and atomically updates the associated task's
    status. This is the primary way an agent signals completion or a state change
    back to the coordinator.

    Args:
        db: SqliteDatabase instance for this project.
        agent_name: Name of the agent sending the result.
        task_id: ID of the task being reported on (optional).
        payload: Result summary or detailed report.
        input_tokens: Fresh input tokens consumed by this run.
        output_tokens: Tokens generated by this run.
        cache_read_tokens: Input served from cache this run.
        cache_write_tokens: Input written to cache this run.
        tool_rounds: API round-trips in this run.
        cost_usd: Total cost in USD.
        status: Status to move the task to (default "done"). Must be in TASK_STATUSES.

    Returns:
        int: Message ID of the logged result.

    Examples:
        >>> reply(db, "claude-worker", 42, "Task completed successfully",
        ...       input_tokens=150, output_tokens=75, cost_usd=0.005)
    """
    msg_id = send_message(
        db, agent_name, HUMAN, task_id, "result", payload,
        input_tokens=input_tokens, output_tokens=output_tokens,
        cache_read_tokens=cache_read_tokens, cache_write_tokens=cache_write_tokens,
        tool_rounds=tool_rounds, cost_usd=cost_usd,
    )
    if task_id is not None:
        if status in ("done", "blocked") and waiting_on_answer(db, task_id):
            # it asked another agent and stopped: claimable again, and run
            # with the answer as context, once the answer task is done
            event = "await_answer"
        elif status == "done":
            event = "finish"  # transition() sends a worktree task to ready_to_merge
        elif status == "blocked":
            event = "block"
        elif status == "needs_approval":
            event = "hold"
        else:
            raise ValueError(f"unknown reply status: {status}")
        transition(db, task_id, event, actor=agent_name)
    return msg_id


def reply_to_task(db: SqliteDatabase, task_id: int, payload: str, sender: str = HUMAN) -> int:
    """Send a human's reply on a task's thread, and reopen it if it was resting.

    This is the human side of the async back-and-forth `reply()` and
    `send_message()` describe for agents: a message alone is invisible until
    the next time the assigned agent's daemon claims a task, and a closed or
    holding task (done, needs_approval, blocked, ready_to_merge) never gets
    reclaimed on its own (see claim_task - it only ever picks up "ready"). So
    a plain note left on a finished task would just sit there unread forever.

    Requeuing to "ready" costs nothing extra: compose_task_prompt() rebuilds
    the next run's prompt from the task's own message thread, so the agent
    sees its prior work plus this reply without re-deriving anything from the
    project itself. A task already "todo", "ready" or "in_progress" is left alone -
    it is waiting for a human, or the agent is working it or about to.

    Args:
        db: SqliteDatabase instance for this project.
        task_id: Task to reply on.
        payload: The reply text.
        sender: Who is replying (default "human").

    Returns:
        int: New message ID.

    Raises:
        ValueError: If the task does not exist.
    """
    task = get_task(db, task_id)
    if not task:
        raise ValueError(f"task {task_id} not found")
    recipient = task["assigned_to"] or HUMAN
    msg_id = send_message(db, sender, recipient, task_id, "note", payload)
    if task["assigned_to"] and task["status"] in TRANSITIONS["requeue"][0]:
        transition(db, task_id, "requeue")
    return msg_id


def is_answer_task(task: dict) -> bool:
    """An answer task is a question one agent put to another (see ask_agent)."""
    return task.get("kind") == "answer"


def is_work_task(task: dict) -> bool:
    return task.get("kind", "work") == "work"


def waiting_on_answer(db: SqliteDatabase, task_id: int) -> bool:
    """Whether this task depends on an answer task that is not done yet."""
    return any(is_answer_task(d) for d in blocking_dependencies(db, task_id))


def ask_agent(db: SqliteDatabase, asker: str, recipient: str, task_id: int | None, question: str) -> int | None:
    """Turn an agent's question to another agent into work that gets done.

    A message alone only surfaces when the recipient next runs a task, which
    for an idle agent is never. So the question becomes a `ready` answer task
    for the recipient, and the asking task depends on it: once the asker stops
    (reply() turns its blocked/done into ready), it is claimable again as soon
    as the answer is in, and the answer reaches it as dependency context.

    Returns the answer task's id, or None when the question stays a plain
    message: the recipient is not an agent, the asking task is not the
    asker's, or the asking task is itself an answer task - one level deep, so
    two agents cannot ping-pong tasks at each other unattended.
    """
    if recipient in (HUMAN, asker) or task_id is None or get_agent(db, recipient) is None:
        return None
    task = get_task(db, task_id)
    if not task or task["assigned_to"] != asker or is_answer_task(task):
        return None
    answer_id = add_task(
        db,
        f"Answer {asker}'s question on task {task_id}",
        (
            f"{asker} is working on task {task_id} ({task['title']}) and asks:\n\n{question}\n\n"
            f"Reply with your answer as the payload; {asker} gets it when task {task_id} resumes."
        ),
        assigned_to=recipient,
        kind="answer",
    )
    transition(db, answer_id, "make_ready", actor=asker)
    add_dependency(db, task_id, answer_id)
    return answer_id


@bound
def latest_result_since(db: SqliteDatabase, agent_name: str, task_id: int, since: float) -> int | None:
    """The newest result this agent logged on this task since `since` - the
    reply it made during a run - or None."""
    found = (
        Message.select(Message.id)
        .where(
            (Message.sender == agent_name)
            & (Message.task_id == task_id)
            & (Message.msg_type == "result")
            & (Message.ts >= since)
        )
        .order_by(Message.ts.desc())
        .first()
    )
    return int(found.id) if found else None


@bound
def record_usage(db: SqliteDatabase, message_id: int, **usage: Any) -> None:
    """Book a run's usage (the ledger's token, round and cost columns) on a message."""
    Message.update(**usage).where(Message.id == message_id).execute()


@bound
def get_inbox(
    db: SqliteDatabase,
    agent_name: str,
    mark_read: bool = True,
    for_task: int | None = None,
) -> list[dict]:
    """Fetch unread messages addressed to this agent, oldest first.

    On each invocation, agents call get_inbox() to learn what the human or other
    agents are asking for. By default, fetched messages are marked as read;
    set mark_read=False to leave them unread for later processing.

    Args:
        db: SqliteDatabase instance for this project.
        agent_name: Agent to fetch messages for.
        mark_read: If True (default), mark fetched messages as read.
        for_task: If given, keep only messages about this task or about no task.

    Returns:
        list[dict]: Unread message records, chronologically ordered. Each has:
                    id, ts, sender, recipient, task_id, msg_type, payload,
                    input_tokens, output_tokens, cost_usd, read_at.

    Examples:
        >>> inbox = get_inbox(db, "claude-worker-1")
        >>> for msg in inbox:
        ...     print(f"{msg['sender']}: {msg['payload']}")
    """
    query = Message.select().where(
        (Message.recipient == agent_name) & Message.read_at.is_null()
    )
    if for_task is not None:
        query = query.where(Message.task_id.is_null() | (Message.task_id == for_task))
    unread = rows(query.order_by(Message.ts))
    if unread and mark_read:
        Message.update(read_at=now()).where(
            Message.id.in_([m["id"] for m in unread])
        ).execute()
    return unread


@bound
def mark_messages_read(db: SqliteDatabase, message_ids: list[int]) -> None:
    """Mark specific messages as read.

    Used to mark inbox messages as read after a successful run, so a message
    is never lost to a run that failed before acting on it.

    Args:
        db: SqliteDatabase instance for this project.
        message_ids: List of message IDs to mark as read.
    """
    if message_ids:
        Message.update(read_at=now()).where(
            Message.id.in_(message_ids)
        ).execute()


@bound
def task_messages(db: SqliteDatabase, task_id: int) -> list[dict]:
    """Fetch all messages related to a task, chronologically.

    Args:
        db: SqliteDatabase instance for this project.
        task_id: Task to query messages for.

    Returns:
        list[dict]: Message records in timestamp order.
    """
    return rows(Message.select().where(Message.task_id == task_id).order_by(Message.ts))
